OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_MODEL_NAME = "qwen3:8b"

USE_FAKE_LLM = False

LLM_TIMEOUT_SECONDS = 240

GENERATE_TEMPERATURE = 0.7
GENERATE_NUM_PREDICT = 500

TRANSFORM_TEMPERATURE = 0.4
TRANSFORM_NUM_PREDICT = 500

CONTINUE_TEMPERATURE = 0.7
CONTINUE_NUM_PREDICT = 500

SPEECH_MODEL_SIZE = "medium"
SPEECH_SAMPLE_RATE = 16000
SPEECH_DEVICE = "cpu"
SPEECH_COMPUTE_TYPE = "int8"
SPEECH_BEAM_SIZE = 10

SHOW_COMMAND_INPUT = True

INTERFACE_LANGUAGE = "de"
TEXT_GENERATION_LANGUAGE = "de"
