# SPDX-License-Identifier: Apache-2.0

"""
Platform-aware filesystem paths for SayScript.

This module centralizes all application-specific paths so the rest of the
application does not need to know whether it is running on Windows or Linux.

Windows:
    Configuration, data, logs, and state are stored below LOCALAPPDATA.

Linux:
    Paths follow the XDG Base Directory convention where possible:
    - XDG_CONFIG_HOME for settings
    - XDG_DATA_HOME for application data
    - XDG_STATE_HOME for logs and auto-save state
"""

import os
import sys
from pathlib import Path

from app.version import APP_NAME


# Lowercase application id used for Linux/XDG paths.
# Example: "SayScript" -> "sayscript"
APP_ID = APP_NAME.lower().replace(" ", "-")


def is_windows() -> bool:
    """Return True when SayScript is running on Windows."""
    return sys.platform.startswith("win")


def is_linux() -> bool:
    """Return True when SayScript is running on Linux."""
    return sys.platform.startswith("linux")


def get_config_dir() -> Path:
    """
    Return the directory for user-editable configuration files.

    This is where SayScript stores settings.json.
    """
    if is_windows():
        base_dir = os.environ.get("LOCALAPPDATA")

        if base_dir:
            return Path(base_dir) / APP_NAME

        return Path.home() / "AppData" / "Local" / APP_NAME

    base_dir = os.environ.get("XDG_CONFIG_HOME")

    if base_dir:
        return Path(base_dir) / APP_ID

    return Path.home() / ".config" / APP_ID


def get_data_dir() -> Path:
    """
    Return the directory for persistent application data.

    On Windows, this currently uses the same directory as configuration.
    On Linux, it follows XDG_DATA_HOME or ~/.local/share.
    """
    if is_windows():
        return get_config_dir()

    base_dir = os.environ.get("XDG_DATA_HOME")

    if base_dir:
        return Path(base_dir) / APP_ID

    return Path.home() / ".local" / "share" / APP_ID


def get_state_dir() -> Path:
    """
    Return the directory for local application state.

    Logs and auto-save files belong here because they are generated by the
    application and are not meant to be manually edited like settings.
    """
    if is_windows():
        return get_config_dir()

    base_dir = os.environ.get("XDG_STATE_HOME")

    if base_dir:
        return Path(base_dir) / APP_ID

    return Path.home() / ".local" / "state" / APP_ID


def get_settings_path() -> Path:
    """Return the full path to SayScript's settings file."""
    return get_config_dir() / "settings.json"


def get_log_dir() -> Path:
    """Return the directory used for rotating log files."""
    return get_state_dir() / "logs"


def get_autosave_dir() -> Path:
    """Return the directory used for auto-save recovery files."""
    return get_state_dir() / "autosave"


def get_autosave_path() -> Path:
    """Return the full path to the current auto-save recovery file."""
    return get_autosave_dir() / "autosave.html"


def ensure_app_dirs() -> None:
    """
    Create all application directories if they do not exist yet.

    This function is safe to call multiple times. It is used during startup,
    settings loading, logging setup, and auto-save operations.
    """
    get_config_dir().mkdir(parents=True, exist_ok=True)
    get_data_dir().mkdir(parents=True, exist_ok=True)
    get_state_dir().mkdir(parents=True, exist_ok=True)
    get_log_dir().mkdir(parents=True, exist_ok=True)
    get_autosave_dir().mkdir(parents=True, exist_ok=True)
